import {
  childCommandNames,
  completionPaths,
  optionsForPath,
  valueOptionNames,
} from "../catalog.js";

export type CompletionShell = "bash" | "zsh";

export function renderShellCompletion(shell: CompletionShell): string {
  return shell === "bash" ? renderBashCompletion() : renderZshCompletion();
}

function renderBashCompletion(): string {
  return `# Generated by shrimpy completion bash
_shrimpy_completion() {
  local cur prev words cword key suggestions value_options
  words=("\${COMP_WORDS[@]}")
  cword=$COMP_CWORD
  cur="\${words[$cword]}"
  prev="\${words[$((cword - 1))]}"
  value_options="${shellWords(valueOptionNames())}"

  case " $value_options " in
    *" $prev "*) return 0 ;;
  esac

  local path=()
  local i skip_next=0
  for ((i = 1; i < cword; i++)); do
    if [[ "$skip_next" == "1" ]]; then
      skip_next=0
      continue
    fi
    case " $value_options " in
      *" \${words[$i]} "*) skip_next=1; continue ;;
    esac
    case "\${words[$i]}" in
      --*) ;;
      -*) ;;
      *) path+=("\${words[$i]}") ;;
    esac
  done
  key="\${path[*]}"

  case "$key" in
${completionCaseLines()}
    *) suggestions="" ;;
  esac

  COMPREPLY=( $(compgen -W "$suggestions" -- "$cur") )
  return 0
}
complete -F _shrimpy_completion shrimpy`;
}

function renderZshCompletion(): string {
  return `#compdef shrimpy
# Generated by shrimpy completion zsh
_shrimpy() {
  local cur prev key suggestions value_options
  cur="\${words[CURRENT]}"
  prev="\${words[$((CURRENT - 1))]}"
  value_options="${shellWords(valueOptionNames())}"

  if [[ " $value_options " == *" $prev "* ]]; then
    return 0
  fi

  local -a path
  local i skip_next=0
  for ((i = 2; i < CURRENT; i++)); do
    if [[ "$skip_next" == "1" ]]; then
      skip_next=0
      continue
    fi
    if [[ " $value_options " == *" \${words[$i]} "* ]]; then
      skip_next=1
      continue
    fi
    case "\${words[$i]}" in
      --*) ;;
      -*) ;;
      *) path+=("\${words[$i]}") ;;
    esac
  done
  key="\${path[*]}"

  case "$key" in
${completionCaseLines()}
    *) suggestions="" ;;
  esac

  compadd -- \${=suggestions}
}
_shrimpy_register_completion() {
  if (( ! $+functions[compdef] )); then
    return 0
  fi

  compdef _shrimpy shrimpy
  precmd_functions=(\${precmd_functions:#_shrimpy_register_completion})
  unfunction _shrimpy_register_completion 2>/dev/null
}

_shrimpy_register_completion
if (( ! $+functions[compdef] )); then
  typeset -ga precmd_functions
  if [[ -z "\${precmd_functions[(r)_shrimpy_register_completion]}" ]]; then
    precmd_functions+=(_shrimpy_register_completion)
  fi
fi

if [[ "\${funcstack[1]:-}" == "_shrimpy" ]]; then
  _shrimpy "$@"
fi`;
}

function completionCaseLines(): string {
  return completionPaths()
    .map((path) => {
      const words = [
        ...childCommandNames(path),
        ...optionsForPath(path).map((option) => option.name),
      ];
      const key = path.join(" ");
      const pattern = key === "" ? "\"\"" : quoteCasePattern(key);
      return `    ${pattern}) suggestions="${shellWords(words)}" ;;`;
    })
    .join("\n");
}

function shellWords(words: readonly string[]): string {
  return [...new Set(words)].sort().join(" ");
}

function quoteCasePattern(value: string): string {
  return `"${value.replace(/(["\\$`])/g, "\\$1")}"`;
}
